---
version: "2.0"

services:
  miner-xmrig:
    image: cryptoandcoffee/akash-xmrig:22
    expose:
      - port: 8080
        as: 80
        proto: tcp
        to:
          - global: true
    env:
      - ALGO=rx/0
      #Set the algorithm you want xmrig to use.
      - POOL=pool.hashvault.pro:443
      #The mining pool you want to connect to.
      - WALLET=4AbG74FRUHYXBLkvqM1f7QH3UXGkhLetKdxS7U7BHkyfMF4nfx99GvN1REwYQHAeVLLy4Qa5gXXkfS4pSHHUWwdVFifDo5K
      #Your Monero Wallet Address for the default pool, otherwise any other wallet address for another pool/coin.
      - WORKER=akash
      #All worker names have the provider domain as suffix, example akash-provider.akash.world
      - PASS=x
      #Most pools do not require a password.  Only change this if you need to set a password.
      - TLS=true
      #Protect your shares by choosing pools that support encryption!
      - TLS_FINGERPRINT=420c7850e09b7c0bdcf748a7da9eb3647daf8515718f36d9ccfdd6b9ff834b14
      #Use a TLS_FINGERPRINT if required.  Can be left blank.
      - RANDOMX_MODE=fast
      #Light or Fast - Min 0.1Gi required for MODE=light and Min 4.75Gi required for MODE=fast
      - CUSTOM_OPTIONS=""
      #Customize the command line options of xmrig.  Full list of command available here:
      #https://xmrig.com/docs/miner/command-line-options
profiles:
  compute:
    miner-xmrig:
      resources:
        cpu:
          units: 6
          #Min 0.01 / Max 256 cpu.units
        memory:
          size: 4.75Gi
          #Min 0.1Gi and MODE=light (Cheapest/slowest/economical)
          #Min 3Gi and MODE=fast with single NUMA nodes (Only works on single NUMA node/limited compatibility)
          #Min 4.75Gi MODE=fast with > 2 NUMA nodes (Best compatibility/fastest)
          #Max 512Gi
          #For best performance use at least 256Mi per cpu.unit requested above the 0.1Gi minimum required.
        storage:
          size: 8Mi
          #Min 8Mi / Max 32Ti
  placement:
    akash:
      pricing:
        miner-xmrig:
          denom: uakt
          amount: 10000 #Keep high to show all bids
deployment:
  miner-xmrig:
    akash:
      profile: miner-xmrig
      count: 1

##Total deployment size cannot exceed 512vCPU / 512Gi / 32Ti
##You can reduce vCPU and increase count:1 to see more bids
##Example: cpu.units:2 and akash.count:10 will show more bids than 10 cpu.units and akash.count 2.
